config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'turns#index'

  resources :turns

  namespace :admin do
    resources :turns
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/turn.rb
class Turn < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/admin/turns_controller.rb
class Admin::TurnsController < ApplicationController
  before_action :admin_check, only: [:index, :update]
  before_action :turn_params, only: [:index, :update]
  def index
    @turns = Turn.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
  end

  def update
    @turn = Turn.find(params[:id])
    respond_to do |format|
      if @turn.update(turn_params)
        format.html 
        format.js 
      end
    end
  end

  private
  def turn_params
    params.permit(:name, :number, :status ).merge(user_id: current_user.id)
  end

  def admin_check
    unless current_user.admin?
      redirect_to root_path
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:user_name ])
  end

end

app/controllers/turns_controller.rb
class TurnsController < ApplicationController
  before_action :now_status, only: [:index, :show]
  before_action :today_create, only:[:index, :show, :new]
  before_action :set_turn, only: [:update, :show]
  before_action :authenticate_user!, only: [:new, :create]
  before_action :admin_check, only: [:update]
  before_action :qrcode, only:[:show]

  def index
    @wait = @today.where(status: "待ち")
    @absence = @today.where(status: "不在")
  end


  def new
    @examinations = Turn.new
    @today_num_end = @today.maximum(:number)
  end

  def create
    @turn = Turn.new(turn_params)
    if @turn.save
      require 'rqrcode'
      text = turn_path(@turn.id)
      @qr = RQRCode::QRCode.new(text).as_svg.html_safe
      render :create
    else
      render :new
    end
  end

  def update
    @turn.update(turn_params)
  end

  def show
    @myturn = @today.where(status: "診察").ids.index(@turn.id)
    @end = @today.where(status: "終了").ids.include?(@turn.id)
    @count = @today.where(status: "待ち").ids.index(@turn.id)
    @absence = @today.where(status: "不在").ids.include?(@turn.id)
  end

  private
  def turn_params
    params.permit(:name, :number, :status ).merge(user_id: current_user.id)
  end

  def set_turn
    @turn = Turn.find(params[:id])
  end

  def today_create
    @today = Turn.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
  end

  def now_status
    @today = Turn.where(created_at: Time.zone.now.beginning_of_day..Time.zone.now.end_of_day)
    @now = @today.where(status: "診察").first
    @wait_people = @today.where(status: "待ち").count
    @absence_people = @today.where(status: "不在").count
  end

  def admin_check
    unless current_user.admin?
      redirect_to root_path
    end
  end

  def qrcode
    require 'rqrcode'
    text = turn_path(@turn.id)
    @qr = RQRCode::QRCode.new(text).as_svg.html_safe
  end

end

app/helpers/admin/turns_helper.rb
module Admin::TurnsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/turns_helper.rb
module TurnsHelper
end

app/views/admin/turns/index.html.erb
<div class="link-issue">
  <div class='link-area'>
    <%= link_to '番号を発行する', new_turn_path, class: 'issue-link' %>
  </div>
</div>
<table>
    <th>番号</th>
    <th>名前</th>
    <th>状態</th>
    <th>変更</th>

 <%@turns.each do|turn|%>
    <tr>
      <td>
        <%=turn.number%>
      </td>
      <td>
        <%=turn.name%>
      </td>
      <td>
        <%=turn.status%>
      </td>
      <td>
        <div class="btn">
          <%= button_to '待ち',  admin_turn_path(turn.id), method: :put, class: "wait-btn", params: {status: '待ち'}, remote: true %>
          <%= button_to '診察',  admin_turn_path(turn.id), method: :put, class: "now-btn", params: {status: '診察'}, remote: true %>
          <%= button_to '不在',  admin_turn_path(turn.id), method: :put, class: "absence-btn", params: {status: '不在'}, remote: true %>
          <%= button_to '終了',  admin_turn_path(turn.id), method: :put, class: "end-btn", params: {status: '終了'}, remote: true %>
        </div>
      </td>
    </tr>
  <%end%>
</table>

<%= link_to 'トップページへ戻る', root_path, {class:'root_path'} %>
<script>
  $('td:contains("待ち")').css("color", "green");
  $('td:contains("診察")').css("color", "red");
  $('td:contains("不在")').css("color", "blue");
</script>

app/views/admin/turns/update.js.erb
location.reload();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTurn</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
  <script>
  const timer = 30000
  window.addEventListener('load',function(){
  setInterval('location.reload()',timer);
  });
</script>
</html>

app/views/turns/create.html.erb
<div class='issue-create'>
  <div class='issue-text'>
    番号が発行されました
  </div>
    <div class="issue-num">
      <%="#{@turn.name}様の番号は#{@turn.number}番です"%>
    </div>
  <div class="qr-position">
    <div class='qr'>
        <%= @qr %>
    </div>
  </div>
    <div class='bottom'>
      <%= '読み込むと待ち状況がわかるページが開けます'%>
      <p><%= link_to "トップページへ戻る", root_path, class: "toppage" %></p>
    </div>
    <div class='reload-notification'>
    <%= 'このページは30秒で自動に切り替わります'%>
    </div>
  </div>

app/views/turns/index.html.erb
<!DOCTYPE html>
<html>
     <%if user_signed_in?%>
        <%= link_to 'ログアウト', destroy_user_session_path, method: :delete, class: "logout-link" %> 
      <% else %>
 
      <%end%>
  <div class='main'> 
  
    <div class='left'>
    
      <div class='left-row'>診察中の番号</div>
        <div class='now'>
          <%if @now.present?%>
            <div class='now-number1'>
              <%= @now.number%>
            </div>
            <div class='now-number2'>番</div>
          <%else%>
            <div class='now-wait'>
              <div class='now-wait1'>番号が表示されるまで</div>
              <div class='now-wait2'>お待ちください</div>
            </div>
            <%end%>
        </div>
        <div class='now-name'>
         <%if @now.present?%>
            <div class='now-name-row'>
              <%= @now.name%>  様
            </div>
          <%end%>
        </div>

        <div class='count'>
          <div class='count-num'>お待ち人数</div>
            <div class='num'>
              <%=@wait_people%> 
            </div>
          <div class='count-num'>人</div>
            <div class='count-num'>不在人数</div>
            <div class='num'>
              <%=@absence_people%>
            </div>
          <div class='count-num'>人</div>

    </div>

      </div>
    
    <div class="right">
      <div class='link-area'>
        <%if user_signed_in?  && current_user.admin?%>
          <%= link_to '管理者ページ', admin_turns_path, class: 'admin-link' %>
        <%elsif user_signed_in?%>
          <%= link_to '番号を発行する', new_turn_path, class: 'issue-link' %>
        <% else %>
          <%= link_to 'ログイン', new_user_session_path, class: "login-link" %>
        <%end%>
      </div>
      <div class='right-row'>
        <div class="table">
          <div class='th'>待ち番号</div>
            
            <% @wait.each do |wait|%>
              <div class="tr">
                <div class='td1'><%= link_to "#{wait.number}番", turn_path(wait.id) %></div>
                <div class='td2'><%= wait.name%>様</div>
              </div>
            <%end%>
        </div>


        <div class="table">
          <div class='th'>不在番号</div>
          <div class='td'>
            <% @absence.each do |absence|%>
              <div class="tr">
                <div class='td1'><%= link_to "#{absence.number}番", turn_path(absence.id) %></div>
                <div class='td2'><%= absence.name%>様</div>
              </div>
            <%end%>
            </div>
        </div>
      </div>
      </div>

</div>
  </div>
  </html>

app/views/turns/new.html.erb
<div class="issue">
  <div class="issue-row">
    <%= form_with model: @turns, url: turns_path, local: true do |f| %>
      <h1>番号を発行する</h1>
      <div class='flex-num'>
          <div class="box-name">
          <%= f.text_field :name, class: 'text-field', placeholder:'名前を入力してください'%>
          </div>
          <% if @today_num_end.present? %>
          <%= f.hidden_field :number,class: 'number' , value: "#{@today_num_end += 1}", :readonly => true %>
          <% else %>
          <%= f.hidden_field :number,class: 'number' , value: "1", :readonly => true %>
          <% end %>
          <div class='box-issue'>
          <%= f.submit "発行" ,class:"submid" %>
          </div>
      </div>
     <% end %>
     <%= link_to 'トップページへ戻る', root_path, {class:'root_path'} %>
  </div>
</div>

app/views/turns/show.html.erb
  <%if @end.present?  %>
    <div class='turn-end'>
      <div class='turn-end-row'> 診察は終了しました</div>
      <p><%= link_to "トップページへ戻る", root_path, class: "toppage" %></p>
    </div>
     
  <%else%>
    <div class='show'>
   
    <div class='user-num'>
    <%= @turn.name %>様の番号は<%= @turn.number %>番です
    </div>
    <div class='show-contents'> 
      <div class="show-num">
        診察中の番号
      </div>

      <% if @now.present? %>
        <div class='show-number'>
          <%= @now.number%>番
        </div>
      <% else %>
        <div class='show-number2'>番号が表示されるまでお待ちください</div>
      <%end%>
    
        <%if @myturn == "診察"%>
          <div class='show-now'>あなたの順番です</div>
        <%elsif @absence.present?%>
         <div class='show-now'>不在でしたので、窓口で確認をしてください</div>
        <%elsif @wait_people >= 0 && @count != 0 %>
        <div class='wait'>
          <%= @turn.name %>様の順番まで、<%= @count %>人待ちです
        </div>
        <p>順番が前後することがあります</p>
        <%else%>
      <div class='show-now'>まもなく順番が参ります</div>
        <%end%>
        <p>不在人数<%= @absence_people%>人</p>
    </div>

    <div class='qr-position'>
      <div class='qr'>
        <%= @qr %>
      </div>
    </div>
    <div class='bottom'>
      <%= '読み込むとこのページを開けます'%>
      <p><%= link_to "トップページへ戻る", root_path, class: "toppage" %></p>
     </div>
   </div>

  <%end%>